# Generated by Django 5.2.3 on 2025-06-14 04:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='ticket',
            new_name='portfolio',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'portfolio')},
        ),
    ]
