# Generated by Django 5.2.3 on 2025-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_contactmessage_rename_ticket_review_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
